2021/07/23 12:56:37 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/23 13:20:31 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/23 13:20:32 [error] [exception.Error] Error: Call to undefined function imagettfbbox() in /var/www/html/web/widgets/captcha/CCaptchaAction.php:208
Stack trace:
#0 /var/www/html/web/widgets/captcha/CCaptchaAction.php(111): CCaptchaAction->renderImage('rmzownh')
#1 /var/www/html/web/CController.php(300): CCaptchaAction->run()
#2 /var/www/html/web/CController.php(278): CController->runAction(Object(CCaptchaAction))
#3 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CCaptchaAction), Array)
#4 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#5 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('site/captcha')
#6 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#7 /var/www/html/testapp/index.php(11): CApplication->run()
#8 {main} REQUEST_URI=/testapp/index.php?r=site/captcha
2021/07/25 11:21:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "captcha".' in /var/www/html/web/CController.php:439
Stack trace:
#0 /var/www/html/web/CController.php(262): CController->missingAction('captcha')
#1 /var/www/html/web/CWebApplication.php(332): CController->run('captcha')
#2 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user/captcha')
#3 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#4 /var/www/html/testapp/index.php(11): CApplication->run()
#5 {main} REQUEST_URI=/testapp/index.php?r=user/captcha
2021/07/25 11:22:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "UserController/captcha".' in /var/www/html/web/CWebApplication.php:336
Stack trace:
#0 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('UserController/...')
#1 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#2 /var/www/html/testapp/index.php(11): CApplication->run()
#3 {main} REQUEST_URI=/testapp/index.php?r=UserController/captcha
2021/07/26 07:46:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:46:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection timed out' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:47:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection timed out' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:48:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:49:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:50:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 07:55:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
2021/07/26 08:00:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] Connection refused' in /var/www/html/db/CDbConnection.php:248
Stack trace:
#0 /var/www/html/db/CDbConnection.php(223): CDbConnection->open()
#1 /var/www/html/db/CDbConnection.php(202): CDbConnection->setActive(true)
#2 /var/www/html/base/CModule.php(353): CDbConnection->init()
#3 /var/www/html/base/CApplication.php(346): CModule->getComponent('db')
#4 /var/www/html/db/ar/CActiveRecord.php(873): CApplication->getDb()
#5 /var/www/html/db/ar/CActiveRecord.php(2179): CActiveRecord->getDbConnection()
#6 /var/www/html/db/ar/CActiveRecord.php(653): CActiveRecordMetaData->__construct(Object(User))
#7 /var/www/html/testapp/protected/models/User.php(19): CActiveRecord::model('User')
#8 /var/www/html/testapp/protected/controllers/UserController.php(116): User::model()
#9 /var/www/html/web/actions/CInlineAction.php(32): UserController->actionList()
#10 /var/www/html/web/CController.php(300): CInlineAction->run()
#11 /var/www/html/web/filters/CFilterChain.php(129): CController->runAction(Object(CInlineAction))
#12 /var/www/html/web/filters/CFilter.php(41): CFilterChain->run()
#13 /var/www/html/web/CController.php(952): CFilter->filter(Object(CFilterChain))
#14 /var/www/html/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#15 /var/www/html/web/filters/CFilterChain.php(126): CInlineFilter->filter(Object(CFilterChain))
#16 /var/www/html/web/CController.php(283): CFilterChain->run()
#17 /var/www/html/web/CController.php(257): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 /var/www/html/web/CWebApplication.php(332): CController->run('')
#19 /var/www/html/web/CWebApplication.php(120): CWebApplication->runController('user')
#20 /var/www/html/base/CApplication.php(134): CWebApplication->processRequest()
#21 /var/www/html/testapp/index.php(11): CApplication->run()
#22 {main} REQUEST_URI=/testapp/index.php?r=user
